services:

  # https://github.com/Azure-Samples/iot-edge-opc-plc
  demo-server:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    ports:
      - 50000:50000
      - 8080:8080 # http://localhost:8080/pn.json
    command: '--pn=50000 --autoaccept --sph --sn=5 --sr=10 --st=uint --fn=5 --fr=1 --ft=uint --gn=5'

  umati-server:
    image: ghcr.io/umati/sample-server:main
    ports:
      - 4840:4840

  # sudo docker pull ghcr.io/opcfoundation/uanetstandard/refserver:latest
  # sudo docker run -it -p 62541:62541 -h $HOSTNAME -v "$(pwd)/OPC Foundation:/root/.local/share/OPC Foundation" ghcr.io/opcfoundation/uanetstandard/refserver:latest -c -s
  reference-server:
    image: ghcr.io/opcfoundation/uanetstandard/refserver:latest
    ports:
      - 62541:62541
    